Create new Groups Directory block for the Block Editor
WPUserManager/wpum-blocks pull request #12
Opened 2021-04-04 19:44 UTC by reygcalantaol

@polevaultweb

2021-04-06 19:46 UTC, reygcalantaol commented
@polevaultweb 
This PR is related to 
https://github.com/WPUserManager/wpum-groups/issues/4

2021-04-19 07:47 UTC, polevaultweb requested changes
@reygcalantaol tested and works great, some comments added

2021-04-19 07:47 UTC, polevaultweb commented on includes/classes/Loader.php
> +		( new GroupDirectory() )->register();
We should only load this block if the Groups addon is active

2021-04-19 07:47 UTC, polevaultweb commented on includes/classes/Blocks/GroupDirectory.php
> +		return [];
We should be able to control the shortcode settings via the block panel
```
'per_page' => 10,
'has_search_form' => 'true',
				'show_public' => 'true',
				'show_private' => 'true',
```

2021-04-19 07:47 UTC, polevaultweb commented on includes/classes/Loader.php
> +		( new GroupDirectory() )->register();
Check for a function or class exists is probably easiest

2021-04-22 10:07 UTC, polevaultweb commented
@reygcalantaol did you see my review?

2021-04-22 12:53 UTC, reygcalantaol commented
@polevaultweb 
I pushed new commits for the updates.

2021-04-22 13:15 UTC, merged